### PR TITLE
Use `LoadWOFFeatureFromReader` instead of `LoadGeoJSONFeatureFromReader`

### LINKED ISSUE #14: Wrong properties in SQLite export
I have the same issue as this one https://github.com/whosonfirst/go-whosonfirst-geojson-v2/pull/3 but now for SQLite exports.

In the spr table I have this kind of entries:

| id | parent_id | name | placetype | country | repo | latitude | longitude | min_latitude | min_longitude | max_latitude | max_longitude | is_current | is_deprecated | is_ceased | is_superseded | is_superseding | superseded_by | supersedes | lastmodified | 
| ---- |  ---- |  ---- |  ---- |  ---- |  ---- |  ---- |  ---- |  ---- |  ---- |  ---- |  ---- |  ---- |  ---- |  ---- |  ---- |  ---- |  ---- |  ---- |  ---- | 
| 504792239 |   | -4193636635226208594 | multipolygon | XX |   | 41.8051579212371 | 14.4903042439064 | 41.7596097025985 | 14.4468571828984 | 41.8051579212371 | 14.5337513049144 | -1 | -1 | -1 | -1 | -1 |   |  | -1 | 
| 504792241 |   | -4193572447443142830 | multipolygon | XX |   | 42.0276133562964 | 14.4233819568573 | 41.9975055758807 | 14.3858960688714 | 42.0276133562964 | 14.4608678448433 | -1 | -1 | -1 | -1 | -1 |   |  | -1 | 
| 504792245 |   | -4193608676583427608 | multipolygon | XX |   | 41.9687105537653 | 14.3517453074848 | 41.9231088221748 | 14.3340265083764 | 41.9687105537653 | 14.3694641065933 | -1 | -1 | -1 | -1 | -1 |   |  | -1 | 
| 504792247 |   | -4193575773305076983 | multipolygon | XX |   | 41.9787497588932 | 14.6030095606378 | 41.8239950739279 | 14.4229290119942 | 41.9787497588932 | 14.7830901092815 | -1 | -1 | -1 | -1 | -1 |   |  | -1 | 
| 504792249 |   | -4193561230255624694 | multipolygon | XX |   | 42.0423777703217 | 14.6872068870061 | 41.9999604211155 | 14.6220947916053 | 42.0423777703217 | 14.7523189824068 | -1 | -1 | -1 | -1 | -1 |   |  | -1 | 
| 504792251 |   | -4193569348419122975 | multipolygon | XX |   | 42.0436589122404 | 14.5697845201179 | 41.9970607914715 | 14.523189156748 | 42.0436589122404 | 14.6163798834877 | -1 | -1 | -1 | -1 | -1 |   |  | -1 | 

names, placetypes, country... looks wrong

### PR DESCRIPTION
**Pull request by Joxit**
I don't know if this repository should be generic or not, but this PR could fix https://github.com/whosonfirst/go-whosonfirst-dist/issues/14

### CODE REVIEW

**Comment by Joxit** [comment]
Hum... This doesn't work on a full planet export....
```
error: Unable to load /whosonfirst-data/data/101/711/881/101711881-alt-quattroshapes_pg.geojson, because Feature is missing a properties.wof:name property
```

:disappointed:

**Comment by thisisaaronland** [comment]
Ah, yes. This needs an extra check for `IsPrincipalWOFRecord` which I will add in a moment:

https://github.com/whosonfirst/go-whosonfirst-index/blob/master/utils/utils.go

**Comment by thisisaaronland** [comment]
This is wrapped up in a bunch of issues around indexing alt files and the go-whosonfirst-geojson-v2 `feature.SPR()` interface so closing for now.

This package has been updated to skip alt files as of release `0.0.3`.

* https://github.com/whosonfirst/go-whosonfirst-geojson-v2/issues/5
* https://github.com/whosonfirst/go-whosonfirst-dist/issues/15

**Comment by Joxit** [comment]
Yeah thanks, I will try this tomorrow!

**Pull request closed without merging**
